development:
  adapter: postgresql
  encoding: utf8
  database: muses
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: tc_test
  pool: 5
  username: postgres
  password:

